// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQCBcRq2bvQuW2o70-SDaoCluvn-drDQ',
    appId: '1:879890589009:web:a2c712522fe910281f5f70',
    messagingSenderId: '879890589009',
    projectId: 'chat-app-dbs10',
    authDomain: 'chat-app-dbs10.firebaseapp.com',
    storageBucket: 'chat-app-dbs10.appspot.com',
    measurementId: 'G-E3YM3091RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3imoNCUb2W6mDiK905WHx_5-UPzq0cg',
    appId: '1:879890589009:android:da5e10b5e17a6a881f5f70',
    messagingSenderId: '879890589009',
    projectId: 'chat-app-dbs10',
    storageBucket: 'chat-app-dbs10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8gKXaO1hKinoKRrZqOLqzc1UH1IZcnc',
    appId: '1:879890589009:ios:bd5e11c60fd3b37c1f5f70',
    messagingSenderId: '879890589009',
    projectId: 'chat-app-dbs10',
    storageBucket: 'chat-app-dbs10.appspot.com',
    iosClientId: '879890589009-o14u71sjfcr9j7f5ik35brq2bv50p0qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8gKXaO1hKinoKRrZqOLqzc1UH1IZcnc',
    appId: '1:879890589009:ios:5bdc1896a5173d731f5f70',
    messagingSenderId: '879890589009',
    projectId: 'chat-app-dbs10',
    storageBucket: 'chat-app-dbs10.appspot.com',
    iosClientId: '879890589009-sqcl7mm0jfqerj21vd5ccm62dv4bslco.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
